version: '2'
services:
  dockerhost:
    image: qoomon/docker-host
    cap_add:
      - ['NET_ADMIN', 'NET_RAW']

  firefox:
    image: selenium/node-firefox:3.141.59-europium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444

  chrome:
    image: selenium/node-chrome:3.141.59-europium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444

  hub:
    image: selenium/hub:3.141.59-europium
    ports:
      - "4444:4444"
