version: '2'
services:
  firefox:
    image: selenium/node-firefox:3.141.59-europium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    networks:
      - selenium_net

  chrome:
    image: selenium/node-chrome:3.141.59-europium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    ports:
      - "5555:5555"
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
      REMOTE_HOST: http://chrome:5555
    networks:
      - selenium_net

  hub:
    image: selenium/hub:3.141.59-europium
    ports:
      - "4444:4444"
    networks:
      - selenium_net

networks:
  selenium_net:
